# Generated by Django 5.2.12 on 2026-04-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationresult',
            name='triggered_rule_descriptions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
