# Generated by Django 5.2.12 on 2026-04-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_moderationresult_triggered_rule_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationresult',
            name='decision_source',
            field=models.CharField(choices=[('ai_auto', 'AI Auto'), ('human_manual', 'Human Manual'), ('human_override', 'Human Override')], default='human_manual', max_length=20),
        ),
        migrations.AddField(
            model_name='moderationresult',
            name='final_decision',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_review', 'Needs Review')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='moderationresult',
            name='moderator_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='moderationresult',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
