# Generated by Django 5.2.12 on 2026-04-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0003_moderationresult_decision_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationresult',
            name='auto_action_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='moderationresult',
            name='auto_action_taken',
            field=models.CharField(choices=[('none', 'None'), ('auto_approved', 'Auto Approved'), ('auto_rejected', 'Auto Rejected'), ('queued_for_review', 'Queued For Review')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='moderationresult',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='moderationresult',
            name='processing_status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='success', max_length=20),
        ),
        migrations.AddField(
            model_name='moderationresult',
            name='prompt_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='moderationresult',
            name='threshold_version',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
